<?php

namespace Iam\Controller;

use Cake\Core\Configure;
use Cake\Event\EventInterface;

/**
 * Class MeController
 * @package Iam\Controller
 *
 * @property \Iam\Model\Table\UsersTable $Users
 * @property \Iam\Service\UserManagerService $UserManager
 */
class MeController extends AppController
{
    public function beforeFilter(EventInterface $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub

        $this->loadService('Iam.UserManager');

        $this->viewBuilder()->setTheme(Configure::read('Themes.backend'));

        $this->Authorization->skipAuthorization();
    }

    public function index()
    {
        $user = $this->UserManager->get($this->Authentication->getIdentity());

        $this->set(compact('user'));
    }
}
